sudo: false
dist: trusty

language: go
go:
- 1.9.2

before_script:
- export GOPATH=$HOME/gopath/src/github.com/Irmine/GoMine

script: go build -i -o gomine.exe src/main.go

notifications:
  email: false